# Generated by Django 5.2.1 on 2025-06-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_alter_language_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='polish_translation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
